version: '3.8'

# This override file fixes monitoring and proxy issues
services:
  # Fixed nginx-proxy with proper network configuration
  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx-simple.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    networks:
      - musicdb-frontend
      - musicdb-backend
      - musicdb-monitoring  # Added to reach Grafana
    depends_on:
      - api-gateway
      - grafana
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Add Prometheus exporters for missing services
  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: postgres-exporter
    restart: always
    environment:
      DATA_SOURCE_NAME: "postgresql://musicdb_user:${POSTGRES_PASSWORD:-musicdb_secure_pass}@postgres:5432/musicdb?sslmode=disable"
    ports:
      - "9187:9187"
    networks:
      - musicdb-backend
      - musicdb-monitoring
    depends_on:
      - postgres

  redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: redis-exporter
    restart: always
    environment:
      REDIS_ADDR: "redis://redis:6379"
    ports:
      - "9121:9121"
    networks:
      - musicdb-backend
      - musicdb-monitoring
    depends_on:
      - redis

    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s


networks:
  musicdb-frontend:
    driver: bridge
  musicdb-backend:
    driver: bridge
  musicdb-monitoring:
    driver: bridge