services:
  local-proxy:
    image: nginx:alpine
    container_name: songnodes-local-proxy
    ports:
      - "8000:80"
    volumes:
      - ./nginx-local-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s