apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: songnodes
build:
  local:
    push: false
  artifacts:
    - image: songnodes/rest-api
      context: services
      docker:
        dockerfile: rest_api/Dockerfile
    - image: songnodes/graph-visualization-api
      context: services/graph-visualization-api
      docker:
        dockerfile: Dockerfile
    - image: songnodes/websocket-api
      context: services
      docker:
        dockerfile: websocket-api/Dockerfile
    - image: songnodes/nlp-processor
      context: services/nlp-processor
      docker:
        dockerfile: Dockerfile
    - image: songnodes/scraper-orchestrator
      context: services/scraper-orchestrator
      docker:
        dockerfile: Dockerfile
    - image: songnodes/metadata-enrichment
      context: .
      docker:
        dockerfile: services/metadata-enrichment/Dockerfile
    - image: songnodes/serato-integration
      context: services/serato-integration
      docker:
        dockerfile: Dockerfile
    - image: songnodes/frontend
      context: frontend
      docker:
        dockerfile: Dockerfile
deploy:
  helm:
    releases:
      - name: songnodes
        namespace: songnodes
        createNamespace: true
        chartPath: deploy/helm/songnodes
        valuesFiles:
          - deploy/helm/songnodes/values-dev.yaml
        setValueTemplates:
          services.restApi.image.repository: "{{.IMAGE_NAME_songnodes_rest_api}}"
          services.restApi.image.tag: "{{.IMAGE_TAG_songnodes_rest_api}}"
          services.graphVisualization.image.repository: "{{.IMAGE_NAME_songnodes_graph_visualization_api}}"
          services.graphVisualization.image.tag: "{{.IMAGE_TAG_songnodes_graph_visualization_api}}"
          services.websocketApi.image.repository: "{{.IMAGE_NAME_songnodes_websocket_api}}"
          services.websocketApi.image.tag: "{{.IMAGE_TAG_songnodes_websocket_api}}"
          services.nlpProcessor.image.repository: "{{.IMAGE_NAME_songnodes_nlp_processor}}"
          services.nlpProcessor.image.tag: "{{.IMAGE_TAG_songnodes_nlp_processor}}"
          services.scraperOrchestrator.image.repository: "{{.IMAGE_NAME_songnodes_scraper_orchestrator}}"
          services.scraperOrchestrator.image.tag: "{{.IMAGE_TAG_songnodes_scraper_orchestrator}}"
          services.metadataEnrichment.image.repository: "{{.IMAGE_NAME_songnodes_metadata_enrichment}}"
          services.metadataEnrichment.image.tag: "{{.IMAGE_TAG_songnodes_metadata_enrichment}}"
          services.seratoIntegration.image.repository: "{{.IMAGE_NAME_songnodes_serato_integration}}"
          services.seratoIntegration.image.tag: "{{.IMAGE_TAG_songnodes_serato_integration}}"
          services.frontend.image.repository: "{{.IMAGE_NAME_songnodes_frontend}}"
          services.frontend.image.tag: "{{.IMAGE_TAG_songnodes_frontend}}"
profiles:
  - name: dev-push
    build:
      local:
        push: true
    deploy:
      helm:
        releases:
          - name: songnodes
            namespace: songnodes
            createNamespace: true
            chartPath: deploy/helm/songnodes
            valuesFiles:
              - deploy/helm/songnodes/values-dev.yaml
            setValueTemplates:
              services.restApi.image.repository: "{{.IMAGE_NAME_songnodes_rest_api}}"
              services.restApi.image.tag: "{{.IMAGE_TAG_songnodes_rest_api}}"
              services.graphVisualization.image.repository: "{{.IMAGE_NAME_songnodes_graph_visualization_api}}"
              services.graphVisualization.image.tag: "{{.IMAGE_TAG_songnodes_graph_visualization_api}}"
              services.websocketApi.image.repository: "{{.IMAGE_NAME_songnodes_websocket_api}}"
              services.websocketApi.image.tag: "{{.IMAGE_TAG_songnodes_websocket_api}}"
              services.nlpProcessor.image.repository: "{{.IMAGE_NAME_songnodes_nlp_processor}}"
              services.nlpProcessor.image.tag: "{{.IMAGE_TAG_songnodes_nlp_processor}}"
              services.scraperOrchestrator.image.repository: "{{.IMAGE_NAME_songnodes_scraper_orchestrator}}"
              services.scraperOrchestrator.image.tag: "{{.IMAGE_TAG_songnodes_scraper_orchestrator}}"
              services.metadataEnrichment.image.repository: "{{.IMAGE_NAME_songnodes_metadata_enrichment}}"
              services.metadataEnrichment.image.tag: "{{.IMAGE_TAG_songnodes_metadata_enrichment}}"
              services.seratoIntegration.image.repository: "{{.IMAGE_NAME_songnodes_serato_integration}}"
              services.seratoIntegration.image.tag: "{{.IMAGE_TAG_songnodes_serato_integration}}"
              services.frontend.image.repository: "{{.IMAGE_NAME_songnodes_frontend}}"
              services.frontend.image.tag: "{{.IMAGE_TAG_songnodes_frontend}}"
  - name: flux
    build:
      local:
        push: true
    deploy:
      helm:
        releases:
          - name: songnodes
            namespace: songnodes
            createNamespace: false
            chartPath: deploy/helm/songnodes
            valuesFiles:
              - deploy/helm/songnodes/values.yaml
            setValues:
              namespace.create: false
              secrets.create: false
            setValueTemplates:
              services.restApi.image.repository: "{{.IMAGE_NAME_songnodes_rest_api}}"
              services.restApi.image.tag: "{{.IMAGE_TAG_songnodes_rest_api}}"
              services.graphVisualization.image.repository: "{{.IMAGE_NAME_songnodes_graph_visualization_api}}"
              services.graphVisualization.image.tag: "{{.IMAGE_TAG_songnodes_graph_visualization_api}}"
              services.websocketApi.image.repository: "{{.IMAGE_NAME_songnodes_websocket_api}}"
              services.websocketApi.image.tag: "{{.IMAGE_TAG_songnodes_websocket_api}}"
              services.nlpProcessor.image.repository: "{{.IMAGE_NAME_songnodes_nlp_processor}}"
              services.nlpProcessor.image.tag: "{{.IMAGE_TAG_songnodes_nlp_processor}}"
              services.scraperOrchestrator.image.repository: "{{.IMAGE_NAME_songnodes_scraper_orchestrator}}"
              services.scraperOrchestrator.image.tag: "{{.IMAGE_TAG_songnodes_scraper_orchestrator}}"
              services.metadataEnrichment.image.repository: "{{.IMAGE_NAME_songnodes_metadata_enrichment}}"
              services.metadataEnrichment.image.tag: "{{.IMAGE_TAG_songnodes_metadata_enrichment}}"
              services.seratoIntegration.image.repository: "{{.IMAGE_NAME_songnodes_serato_integration}}"
              services.seratoIntegration.image.tag: "{{.IMAGE_TAG_songnodes_serato_integration}}"
              services.frontend.image.repository: "{{.IMAGE_NAME_songnodes_frontend}}"
              services.frontend.image.tag: "{{.IMAGE_TAG_songnodes_frontend}}"
