namespace:
  create: false

secrets:
  create: false

postgres:
  persistence:
    enabled: false

redis:
  persistence:
    enabled: false

rabbitmq:
  persistence:
    enabled: false

services:
  restApi:
    replicaCount: 1
    image:
      pullPolicy: IfNotPresent
    resources:
      requests:
        memory: 192Mi
        cpu: 80m
      limits:
        memory: 384Mi
        cpu: 400m
  graphVisualization:
    enabled: false
  websocketApi:
    replicaCount: 1
    image:
      pullPolicy: IfNotPresent
  nlpProcessor:
    enabled: false
  scraperOrchestrator:
    enabled: false
  metadataEnrichment:
    replicaCount: 1
    image:
      pullPolicy: IfNotPresent
    resources:
      requests:
        memory: 384Mi
        cpu: 150m
      limits:
        memory: 768Mi
        cpu: 600m
  seratoIntegration:
    enabled: false
    persistence:
      enabled: false
  frontend:
    replicaCount: 1
    image:
      pullPolicy: IfNotPresent
    resources:
      requests:
        memory: 96Mi
        cpu: 50m
      limits:
        memory: 192Mi
        cpu: 200m

autoscaling:
  enabled: false

ingress:
  enabled: false
