global:
  # SMTP disabled for development environment - no email server available
  # smtp_smarthost: 'localhost:587'
  # smtp_from: 'songnodes-alerts@localhost'
  # smtp_auth_username: ''
  # smtp_auth_password: ''

  # Default notification templates
  resolve_timeout: 5m

# Routing configuration
route:
  group_by: ['alertname', 'severity', 'component']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'default-receiver'

  # Routing tree for different alert types
  routes:
    # Critical alerts - immediate notification
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 10s
      repeat_interval: 30m

    # Enrichment pipeline alerts
    - match:
        component: enrichment_pipeline
      receiver: 'enrichment-team'
      group_by: ['alertname', 'provider', 'field_category']
      group_interval: 5m
      routes:
        # Critical enrichment issues
        - match:
            severity: critical
          receiver: 'critical-alerts'
          group_wait: 10s
        # Waterfall efficiency warnings
        - match:
            category: efficiency
          receiver: 'enrichment-team'
          group_interval: 10m

    # API Gateway and resilience alerts
    - match:
        component: api_gateway
      receiver: 'api-team'
      group_by: ['alertname', 'provider']
      group_interval: 3m
      routes:
        # Circuit breaker events
        - match:
            category: resilience
          receiver: 'api-team'
          group_wait: 30s

    # DLQ management alerts
    - match:
        component: dlq_manager
      receiver: 'dlq-team'
      group_by: ['alertname', 'queue_name']
      group_interval: 5m
      routes:
        # Critical DLQ depth
        - match:
            severity: critical
          receiver: 'critical-alerts'
          group_wait: 10s

    # Medallion architecture alerts
    - match_re:
        alertname: '(BronzeToSilverLagHigh|SilverToGoldLagHigh|SilverDataQualityLow)'
      receiver: 'data-engineering-team'
      group_by: ['alertname', 'layer']
      group_interval: 10m

    # Infrastructure alerts
    - match:
        component: infrastructure
      receiver: 'infrastructure-team'
      group_interval: 2m

    # Data platform alerts
    - match:
        team: data-platform
      receiver: 'data-platform-team'
      group_interval: 3m

    # Performance alerts (less urgent)
    - match:
        component: api
      receiver: 'backend-team'
      group_interval: 10m

    # Cost monitoring alerts
    - match:
        category: cost
      receiver: 'finance-team'
      group_interval: 30m
      repeat_interval: 12h

    # Data quality alerts
    - match:
        category: data_quality
      receiver: 'data-quality-team'
      group_interval: 15m

    # Info level alerts (batched)
    - match:
        severity: info
      receiver: 'info-alerts'
      group_interval: 15m
      repeat_interval: 12h

# Alert receivers/notification channels - Development Mode
# All notifications disabled for development environment
# Alerts are logged in Alertmanager UI only
receivers:
  # Default receiver (fallback)
  - name: 'default-receiver'
    # Development: No email configured
    # For production: Add email_configs here

  # Critical alerts - multiple channels
  - name: 'critical-alerts'
    # Development: No notifications configured
    # For production: Add email_configs and webhook_configs here

  # Enrichment pipeline team
  - name: 'enrichment-team'
    # Development: No notifications configured
    # For production: Add email_configs for enrichment team

  # API Gateway team
  - name: 'api-team'
    # Development: No notifications configured
    # For production: Add email_configs for API team

  # DLQ management team
  - name: 'dlq-team'
    # Development: No notifications configured
    # For production: Add email_configs for DLQ team

  # Data engineering team (Medallion architecture)
  - name: 'data-engineering-team'
    # Development: No notifications configured
    # For production: Add email_configs for data engineering team

  # Finance team (cost alerts)
  - name: 'finance-team'
    # Development: No notifications configured
    # For production: Add email_configs for finance team

  # Data quality team
  - name: 'data-quality-team'
    # Development: No notifications configured
    # For production: Add email_configs for data quality team

  # Infrastructure team notifications
  - name: 'infrastructure-team'
    # Development: No notifications configured
    # For production: Add email_configs here

  # Data platform team notifications
  - name: 'data-platform-team'
    # Development: No notifications configured
    # For production: Add email_configs here

  # Backend team for API issues
  - name: 'backend-team'
    # Development: No notifications configured
    # For production: Add email_configs here

  # Info alerts - batched summary
  - name: 'info-alerts'
    # Development: No notifications configured
    # For production: Add email_configs here

# Inhibition rules to reduce noise
inhibit_rules:
  # If service is down, don't alert on high latency for same service
  - source_match:
      alertname: ServiceDown
    target_match:
      alertname: APIHighLatency
    equal: ['instance']

  # If there's a critical database issue, don't alert on query latency
  - source_match:
      severity: critical
      component: database
    target_match:
      alertname: DatabaseHighLatency
    equal: ['instance']

  # If scraper has high error rate, don't alert on low activity
  - source_match:
      alertname: ScraperHighErrorRate
    target_match:
      alertname: ScraperLowActivity
    equal: ['scraper']

  # Circuit breaker inhibitions
  # If circuit breaker is open, don't alert on API errors for same provider
  - source_match:
      alertname: CircuitBreakerOpen
    target_match_re:
      alertname: '(EnrichmentAPIHighErrorRate|ProviderResponseTimeSlow)'
    equal: ['provider']

  # If circuit breaker is flapping, suppress related alerts
  - source_match:
      alertname: CircuitBreakerFlapping
    target_match:
      alertname: CircuitBreakerOpen
    equal: ['provider']

  # DLQ inhibitions
  # If DLQ depth is critical, don't alert on high depth warning
  - source_match:
      alertname: DLQDepthCritical
    target_match:
      alertname: DLQDepthHigh
    equal: ['queue']

  # If DLQ is full, don't alert on replay failures
  - source_match:
      alertname: DLQDepthCritical
    target_match:
      alertname: DLQReplayFailureRateHigh
    equal: ['queue']

  # Enrichment pipeline inhibitions
  # If provider is completely failing, suppress related warnings
  - source_match:
      alertname: WaterfallProviderFailure
    target_match_re:
      alertname: '(WaterfallFallbackRateHigh|EnrichmentAPIHighErrorRate)'
    equal: ['provider']

  # If data quality is critically low, suppress completeness warnings
  - source_match:
      alertname: SilverDataQualityLow
      severity: critical
    target_match:
      alertname: EnrichmentCompletenessCritical
    equal: ['layer']

  # If Bronze->Silver lag is critical, suppress Gold materialization lag
  - source_match:
      alertname: BronzeToSilverLagHigh
      severity: critical
    target_match:
      alertname: SilverToGoldLagHigh

# Templates for custom formatting
templates:
  - '/etc/alertmanager/templates/*.tmpl'