global:
  # SMTP disabled for development environment - no email server available
  # smtp_smarthost: 'localhost:587'
  # smtp_from: 'songnodes-alerts@localhost'
  # smtp_auth_username: ''
  # smtp_auth_password: ''

  # Default notification templates
  resolve_timeout: 5m

# Routing configuration
route:
  group_by: ['alertname', 'severity', 'component']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'default-receiver'

  # Routing tree for different alert types
  routes:
    # Critical alerts - immediate notification
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 10s
      repeat_interval: 30m

    # Infrastructure alerts
    - match:
        component: infrastructure
      receiver: 'infrastructure-team'
      group_interval: 2m

    # Data platform alerts
    - match:
        team: data-platform
      receiver: 'data-platform-team'
      group_interval: 3m

    # Performance alerts (less urgent)
    - match:
        component: api
      receiver: 'backend-team'
      group_interval: 10m

    # Info level alerts (batched)
    - match:
        severity: info
      receiver: 'info-alerts'
      group_interval: 15m
      repeat_interval: 12h

# Alert receivers/notification channels - Development Mode
# All notifications disabled for development environment
# Alerts are logged in Alertmanager UI only
receivers:
  # Default receiver (fallback)
  - name: 'default-receiver'
    # Development: No email configured
    # For production: Add email_configs here

  # Critical alerts - multiple channels
  - name: 'critical-alerts'
    # Development: No notifications configured
    # For production: Add email_configs and webhook_configs here

  # Infrastructure team notifications
  - name: 'infrastructure-team'
    # Development: No notifications configured
    # For production: Add email_configs here

  # Data platform team notifications
  - name: 'data-platform-team'
    # Development: No notifications configured
    # For production: Add email_configs here

  # Backend team for API issues
  - name: 'backend-team'
    # Development: No notifications configured
    # For production: Add email_configs here

  # Info alerts - batched summary
  - name: 'info-alerts'
    # Development: No notifications configured
    # For production: Add email_configs here

# Inhibition rules to reduce noise
inhibit_rules:
  # If service is down, don't alert on high latency for same service
  - source_match:
      alertname: ServiceDown
    target_match:
      alertname: APIHighLatency
    equal: ['instance']

  # If there's a critical database issue, don't alert on query latency
  - source_match:
      severity: critical
      component: database
    target_match:
      alertname: DatabaseHighLatency
    equal: ['instance']

  # If scraper has high error rate, don't alert on low activity
  - source_match:
      alertname: ScraperHighErrorRate
    target_match:
      alertname: ScraperLowActivity
    equal: ['scraper']

# Templates for custom formatting
templates:
  - '/etc/alertmanager/templates/*.tmpl'