groups:
  - name: browser_collector_alerts
    interval: 30s
    rules:
      # High memory usage alert
      - alert: BrowserCollectorHighMemory
        expr: container_memory_usage_bytes{container="browser-collector"} > 1.8e9
        for: 5m
        labels:
          severity: warning
          service: browser-collector
        annotations:
          summary: "Browser Collector high memory usage"
          description: "Browser collector using {{ humanize $value }} bytes (>90% of 2GB limit)"

      # Critical memory usage alert
      - alert: BrowserCollectorCriticalMemory
        expr: container_memory_usage_bytes{container="browser-collector"} > 1.9e9
        for: 2m
        labels:
          severity: critical
          service: browser-collector
        annotations:
          summary: "Browser Collector CRITICAL memory usage"
          description: "Browser collector using {{ humanize $value }} bytes (>95% of 2GB limit) - may crash soon"

      # Too many queued collections
      - alert: BrowserCollectorHighQueueDepth
        expr: queued_collections > 10
        for: 5m
        labels:
          severity: warning
          service: browser-collector
        annotations:
          summary: "Browser Collector queue depth high"
          description: "{{ $value }} collections waiting for browser slot - consider scaling"

      # High failure rate
      - alert: BrowserCollectorHighFailureRate
        expr: |
          (
            rate(collection_tasks_total{status="failed"}[5m])
            /
            rate(collection_tasks_total[5m])
          ) > 0.2
        for: 10m
        labels:
          severity: warning
          service: browser-collector
        annotations:
          summary: "Browser Collector high failure rate"
          description: "{{ humanizePercentage $value }} of collections failing in last 5 minutes"

      # Service down
      - alert: BrowserCollectorDown
        expr: up{job="browser-collector"} == 0
        for: 2m
        labels:
          severity: critical
          service: browser-collector
        annotations:
          summary: "Browser Collector service is down"
          description: "Browser collector has been down for more than 2 minutes"

      # Slow collections (p95 latency > 2 minutes)
      - alert: BrowserCollectorSlowCollections
        expr: histogram_quantile(0.95, rate(collection_duration_seconds_bucket[5m])) > 120
        for: 10m
        labels:
          severity: warning
          service: browser-collector
        annotations:
          summary: "Browser Collector slow collections"
          description: "95th percentile collection time is {{ humanizeDuration $value }} (>2 minutes)"

      # Active collections at max capacity
      - alert: BrowserCollectorAtCapacity
        expr: active_collections >= 3
        for: 15m
        labels:
          severity: info
          service: browser-collector
        annotations:
          summary: "Browser Collector at max capacity"
          description: "All {{ $value }} browser slots in use for >15 minutes - consider scaling"

      # Extraction failures
      - alert: BrowserCollectorExtractionFailures
        expr: |
          (
            rate(extraction_tasks_total{status="failed"}[10m])
            /
            rate(extraction_tasks_total[10m])
          ) > 0.3
        for: 15m
        labels:
          severity: warning
          service: browser-collector
        annotations:
          summary: "Browser Collector high extraction failure rate"
          description: "{{ humanizePercentage $value }} of LLM extractions failing"

      # No collections in last hour (might indicate integration issue)
      - alert: BrowserCollectorNoActivity
        expr: rate(collection_tasks_total[1h]) == 0
        for: 1h
        labels:
          severity: info
          service: browser-collector
        annotations:
          summary: "Browser Collector no activity"
          description: "No collection tasks in the last hour - check integration"
