apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://metrics-prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"
      queryTimeout: "60s"
      httpMethod: "GET"

  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: musicdb
    user: musicdb_user
    secureJsonData:
      password: ${POSTGRES_PASSWORD:-musicdb_secure_pass}
    jsonData:
      sslmode: "disable"
      maxOpenConns: 100
      maxIdleConns: 100
      connMaxLifetime: 14400

  - name: Redis
    type: redis-datasource
    access: proxy
    url: redis://redis:6379
    jsonData:
      client: "standalone"
      poolSize: 5
      timeout: 10
      pingInterval: 0
    secureJsonData:
      password: ${REDIS_PASSWORD:-redis_secure_pass_2024}

  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "logstash-*"
    jsonData:
      interval: "Daily"
      timeField: "@timestamp"
      esVersion: "8.11.0"
      maxConcurrentShardRequests: 5