---
apiVersion: v1
kind: Service
metadata:
  name: graph-visualization-service
  namespace: songnodes
  labels:
    app.kubernetes.io/name: graph-visualization
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  ports:
    - port: 8084
      targetPort: 8084
      protocol: TCP
      name: http
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: graph-visualization
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: graph-visualization
  namespace: songnodes
  labels:
    app.kubernetes.io/name: graph-visualization
    app.kubernetes.io/component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: graph-visualization
  template:
    metadata:
      labels:
        app.kubernetes.io/name: graph-visualization
        app.kubernetes.io/component: backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
    spec:
      containers:
        - name: graph-visualization
          image: songnodes/graph-visualization-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8084
              name: http
            - containerPort: 9090
              name: metrics
          envFrom:
            - configMapRef:
                name: songnodes-config
            - secretRef:
                name: songnodes-secrets
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8084
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8084
            initialDelaySeconds: 10
            periodSeconds: 5